- hosts: avi.slave.com
  tasks:
  - package:
          name: httpd
          state: present
  - copy:
          src: index.html
          dest: /var/www/html
  - service:
          name: httpd
          state: started
